module ModelNames
  MODELS = { "Will" => Will,
             "Trust" => Trust,
             "Legal" => PowerOfAttorney,
             "2017" => Tax,
             "2016" => Tax,
             "2015" => Tax,
             "2014" => Tax,
             "2013" => Tax,
             "2012" => Tax,
             "2011" => Tax,
             "2010" => Tax,
             "Burial" => FinalWish,
             "Charity" => FinalWish,
             "Cremation" => FinalWish,
             "Ethical Will" => FinalWish,
             "Funeral / Memorial" => FinalWish,
             "Items to Destroy" => FinalWish,
             "Miscellaneous" => FinalWish,
             "Obituary" => FinalWish,
             "Organ Donor" => FinalWish,
             "Pet Care" => FinalWish,
             "Veterans" => FinalWish }
end