common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *common
  database: zoku_vault_development

test:
  <<: *common
  database: zoku_vault_test

production:
  <<: *common
  database: zoku_vault_production
  username: zoku_vault_production
  password: <%= ENV['ZOKU_VAULT_DATABASE_PASSWORD'] %>
