from_env: &from_env
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  filepicker_api_key: <%= ENV['FILEPICKER_API_KEY'] %>
  filepicker_secret: <%= ENV['FILEPICKER_SECRET'] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *from_env

development:
  <<: *from_env
  secret_key_base: 3c1e2a663a42d28ba4027ddf0e22bcfe67c634ff8e3b1bcc0a45c736c0ff15a5dd094f6b317a4952b30967c61e22845a357e1e1c76c1966a52a481efe154270f
  filepicker_api_key: 'AVSi48ZIUQlqdLknJzFrMz'
  filepicker_secret: 'IZZO6S3M7BANJOK4DEWHIOQNY4'

test:
  secret_key_base: 4d95eb84f900147ecb4fce1f545675be1651f9140b4db798874fb031c4f4705395852173949b559d4bf7065ee89c9ce9abca51c1646d1266b20f6403998e2623
