# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

from_env: &from_env
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  aws_user_key_id: <%= ENV['AWS_USER_ACCESS_KEY_ID'] %>
  aws_user_secret_key: <%= ENV['AWS_USER_SECRET_ACCESS_KEY'] %>
  aws_crypto_user_key_id: <%= ENV['AWS_CRYPTO_USER_ACCESS_KEY_ID'] %>
  aws_crypto_user_secret_key: <%= ENV['AWS_CRYPTO_USER_SECRET_ACCESS_KEY'] %>
  aws_access_role: <%= ENV['AWS_ACCESS_ROLE_ARN'] %>
  aws_region: <%= ENV['AWS_REGION'] %>
  aws_bucket_name: <%= ENV['S3_BUCKET'] %>
  filepicker_api_key: <%= ENV['FILEPICKER_API_KEY'] %>
  filepicker_secret: <%= ENV['FILEPICKER_SECRET'] %>
  online_accounts_secret_key: <%= ENV['ONLINE_ACCOUNTS_SECRET_KEY'] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *from_env
  aws_per_user_key_alias: 'alias/per-user-at-rest'
  aws_per_user_key_role: 'arn:aws:iam::751141858228:role/per-user-crypto-role'

development:
  <<: *from_env
  secret_key_base: 3c1e2a663a42d28ba4027ddf0e22bcfe67c634ff8e3b1bcc0a45c736c0ff15a5dd094f6b317a4952b30967c61e22845a357e1e1c76c1966a52a481efe154270f
  aws_user_key_id: 'AKIAI5ZT3G4SNX4BRHRA'
  aws_user_secret_key: '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'
  aws_access_role: 'arn:aws:iam::751141858228:role/s3access'
  aws_bucket_name: 'zoku-stage'
  aws_region: 'us-east-1'
  aws_per_user_key_alias: 'alias/per-user-at-rest-dev'
  aws_per_user_key_role: 'arn:aws:iam::751141858228:role/per-user-crypto-dev-role'
  filepicker_api_key: 'AU8hye5meSjiQ6l5oOxKFz'
  filepicker_secret: '73R7FY6GYFEH5PZXJW4OLADTLM'
  online_accounts_secret_key: 'drC3eNzXeR/y2mLzHOa/5pM5GjyVJg3v6PdVo7YNjW0='

test:
  secret_key_base: 4d95eb84f900147ecb4fce1f545675be1651f9140b4db798874fb031c4f4705395852173949b559d4bf7065ee89c9ce9abca51c1646d1266b20f6403998e2623
  aws_user_key_id: 'AKIAJVN475LRRGCMK3IA'
  aws_user_secret_key: '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'
  aws_access_role: 'arn:aws:iam::751141858228:role/s3access'
  aws_bucket_name: 'zoku-stage'
  aws_region: 'us-east-1'
  filepicker_api_key: 'AU8hye5meSjiQ6l5oOxKFz'
  filepicker_secret: '73R7FY6GYFEH5PZXJW4OLADTLM'
