# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c1e2a663a42d28ba4027ddf0e22bcfe67c634ff8e3b1bcc0a45c736c0ff15a5dd094f6b317a4952b30967c61e22845a357e1e1c76c1966a52a481efe154270f

test:
  secret_key_base: 4d95eb84f900147ecb4fce1f545675be1651f9140b4db798874fb031c4f4705395852173949b559d4bf7065ee89c9ce9abca51c1646d1266b20f6403998e2623

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
