require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe RelationshipsController, type: :controller do

  let(:valid_attributes) do
    { name: Faker::Name.name, relationship: "personal"}
  end

  let(:invalid_attributes) do
    skip("No current validations on the model associated with this controller")
  end

  before { sign_in create(:user) }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RelationshipsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all relationships as @relationships" do
      relationship = create(:relationship)
      get :index, {}, valid_session
      expect(assigns(:relationships)).to eq([relationship])
    end
  end

  describe "GET #show" do
    it "assigns the requested relationship as @relationship" do
      relationship = create(:relationship)
      get :show, {id: relationship.to_param}, valid_session
      expect(assigns(:relationship)).to eq(relationship)
    end
  end

  describe "GET #new" do
    it "assigns a new relationship as @relationship" do
      get :new, {}, valid_session
      expect(assigns(:relationship)).to be_a_new(Relationship)
    end
  end

  describe "GET #edit" do
    it "assigns the requested relationship as @relationship" do
      relationship = create(:relationship)
      get :edit, {id: relationship.to_param}, valid_session
      expect(assigns(:relationship)).to eq(relationship)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Relationship" do
        expect {
          post :create, {relationship: valid_attributes}, valid_session
        }.to change(Relationship, :count).by(1)
      end

      it "assigns a newly created relationship as @relationship" do
        post :create, {relationship: valid_attributes}, valid_session
        expect(assigns(:relationship)).to be_a(Relationship)
        expect(assigns(:relationship)).to be_persisted
      end

      it "redirects to the created relationship" do
        post :create, {relationship: valid_attributes}, valid_session
        expect(response).to redirect_to(assigns(:relationship))
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved relationship as @relationship" do
        post :create, {relationship: invalid_attributes}, valid_session
        expect(assigns(:relationship)).to be_a_new(Relationship)
      end

      it "re-renders the 'new' template" do
        post :create, {relationship: invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    let(:new_name) { Faker::Name.name }
    let(:new_valid_attributes) { valid_attributes.merge({ name: new_name }) }
    let(:new_invalid_attributes) do
      skip("No current validations on the model associated with this controller")
    end

    context "with valid params" do
      it "updates the requested relationship" do
        relationship = create(:relationship)
        put :update, {id: relationship.to_param, relationship: new_valid_attributes}, valid_session
        relationship.reload
        expect(relationship.name).to eq(new_name)
      end

      it "assigns the requested relationship as @relationship" do
        relationship = create(:relationship)
        put :update, {id: relationship.to_param, relationship: new_valid_attributes}, valid_session
        expect(assigns(:relationship)).to eq(relationship)
      end

      it "redirects to the relationship" do
        relationship = create(:relationship)
        put :update, {id: relationship.to_param, relationship: new_valid_attributes}, valid_session
        expect(response).to redirect_to(relationship)
      end
    end

    context "with invalid params" do
      it "assigns the relationship as @relationship" do
        relationship = create(:relationship)
        put :update, {id: relationship.to_param, relationship: new_invalid_attributes}, valid_session
        expect(assigns(:relationship)).to eq(relationship)
      end

      it "re-renders the 'edit' template" do
        relationship = create(:relationship)
        put :update, {id: relationship.to_param, relationship: new_invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested relationship" do
      relationship = create(:relationship)
      expect {
        delete :destroy, {id: relationship.to_param}, valid_session
      }.to change(Relationship, :count).by(-1)
    end

    it "redirects to the relationships list" do
      relationship = create(:relationship)
      delete :destroy, {id: relationship.to_param}, valid_session
      expect(response).to redirect_to(relationships_url)
    end
  end

end
